/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.ai.spring.ai.starter.model.openai)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.data.jdbc)
    api(libs.org.springframework.boot.spring.boot.starter.websocket)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.io.jsonwebtoken.jjwt)
    api(libs.org.mapstruct.mapstruct)
    api(libs.org.projectlombok.lombok.mapstruct.binding)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    compileOnly(libs.javax.xml.bind.jaxb.api)
    compileOnly(libs.org.mapstruct.mapstruct.processor)
}

group = "tech.studease"
version = "0.0.1-SNAPSHOT"
description = "studease"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
